### ISSUE TITLE
Parser Fails with Credit Card Transactions

### ISSUE THREAD

**Issue by mattcdavis1** [asgrim/ofxparser#10]
I'm not sure if this library is attempting to support credit card transactions, but currenty when downloading a qfx file from bank of america for my credit card, the parser fails.  The reason is that the transaction wrapper key is CREDITCARDMSGSRSV1 rather than BANKMSGSRSV1.  Additionally, the next level deep is CCSTMTRS rather than STMTRS.

here is a sample:  https://gist.github.com/mattcdavis1/3945e88d8bf931c541f2

**Comment by avinashjoshi** [comment]
I faced the same and the parser does not seem to parse credit card accounts, only bank accounts. Is someone working on this already?

**Comment by mattcdavis1** [comment]
i've forked the repo and added support for credit cards here:

https://github.com/mattcdavis1/ofxparser

**Comment by asgrim** [comment]
PRs welcome ;)

**Comment by mattcdavis1** [comment]
just created a pull request.
