### ISSUE TITLE
Looking in wrong tag for credit card account info?

### ISSUE THREAD

**Issue by spekary** [asgrim/ofxparser#16]
In BuildCreditAccount, you are using $xml->CCSTMTRS->BANKACCTFROM. My statement has this:

$xml->CCSTMTRS->CCACCTFROM

Perhaps different credit card companies use different ones? Or is this just a bug?

**Comment by asgrim** [comment]
Quite possibly just different fields being used; the number of inconsistencies in OFX generation is huge.

https://github.com/asgrim/ofxparser/blob/master/lib/OfxParser/Ofx.php#L172 is probably what we're looking for, although I'd say we need to support OFX with `BANKACCTFROM` as well still >.<

**Comment by asgrim** [comment]
We can probably put a check for the correct node name into https://github.com/asgrim/ofxparser/blob/master/lib/OfxParser/Ofx.php#L189
