### ISSUE TITLE
Investment Accounts OFX not parsing

### ISSUE THREAD

**Issue by billm950** [asgrim/ofxparser#37]
Downloaded Merrill Lynch OFX file and results are blank.

Example file:
OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:TYPE1
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

`<OFX>
  <SIGNONMSGSRSV1>
    <SONRS>
      <STATUS>
        <CODE>0
        <SEVERITY>INFO
        <MESSAGE>SUCCESS
      </STATUS>
      <DTSERVER>20170204082107.751[-5:EST]
      <LANGUAGE>ENG
      <DTPROFUP>20170204082107.751[-5:EST]
      <FI>
        <ORG>Merrill Lynch &amp; Co., Inc.
        <FID>5550
      </FI>
      <INTU.BID>5550
      <INTU.USERID>xxxxxxxxxxx
    </SONRS>
  </SIGNONMSGSRSV1>
  <INVSTMTMSGSRSV1>
    <INVSTMTTRNRS>
      <TRNUID>0
      <STATUS>
        <CODE>0
        <SEVERITY>INFO
        <MESSAGE>SUCCESS
      </STATUS>
      <INVSTMTRS>
        <DTASOF>20170204082107.821[-5:EST]
        <CURDEF>USD</CURDEF>
        <INVACCTFROM>
          <BROKERID>www.mldirect.ml.com
          <ACCTID>99Z99999
        </INVACCTFROM>
        <INVTRANLIST>
          <DTSTART>20170104110000.000[-5:EST]
          <DTEND>20170203110000.000[-5:EST]
          <INVBANKTRAN>
            <STMTTRN>
              <TRNTYPE>CREDIT
              <DTPOSTED>20170203110000.000[-5:EST]</DTPOSTED>
              <TRNAMT>10
              <FITID>20170203AF180757320068440
              <NAME>Funds Transfer
              <MEMO>FR BAC#99999999999999
            </STMTTRN>
            <SUBACCTFUND>CASH
          </INVBANKTRAN>
        </INVTRANLIST>
        <INVBAL>
          <AVAILCASH>10
          <MARGINBALANCE>0
          <SHORTBALANCE>0
          <BUYPOWER>0
        </INVBAL>
      </INVSTMTRS>
    </INVSTMTTRNRS>
  </INVSTMTMSGSRSV1>
</OFX>`

**Comment by asgrim** [comment]
Yeah I'd like to support these, this is a duplicate of #15 though. I did start a WIP pull request in #30 to add this but I didn't get very far and haven't had much time since unfortunately :/ Please do watch issue #15 though for updates, and happy to accept PRs for this also ;)
