### ISSUE TITLE
Open <MEMO> with symbol " closeUnclosedXmlTags don't add </MEMO>

### ISSUE THREAD

**Issue by renatomb** [asgrim/ofxparser#49]
Got an error when tried to import a credit card statement, failing to parse OFX. 

Debugging I got the message Opening and ending tag mismatch: MEMO line 68 and STMTTRN.

When I verified the OFX file, I noticed that this line has a " symbol in it. When I removed it from my original file, everything worked fine.

Debugging parser I saw that closeUnclosedXmlTags is not working when there is a " symbol.

![bug-parserofx](https://user-images.githubusercontent.com/30217311/47589742-6c207180-d940-11e8-9bf3-089ef44dc657.jpg)

**Comment by asgrim** [comment]
Fixed by #50
