### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by asgrim** [asgrim/ofxparser#62]
Hi folks; unfortunately, I just don't have the time or inclination to maintain this any more. I've kept telling myself I'll get around to modernising this, but as I'm no longer using this on any projects, it's unlikely I'll ever get around to it.

I'm happy for someone to fork this, take it over etc., but I won't be maintaining it any more (not that I was doing much with it anyway...

Opinions/thoughts/suggestions welcome. Previous contributors would be favoured.

I will mark this repo as archived in ~2 weeks.

**Comment by nilsonpena** [comment]
:(

Em ter., 25 de ago. de 2020 às 10:05, James Titcumb <
notifications@github.com> escreveu:

**Comment by asgrim** [comment]
Since there has been no take-up, I am abandoning this project on Packagist and archiving it on GitHub. If someone else forks and regularly maintains, I'm happy to provide a replacement package marker on Packagist. Thanks folks!
